### ISSUE TITLE
Add display: none rules for rilmPerson@type='inverted' and rilmPerson@type='full' to mgg CSS

### ISSUE THREAD

**Issue by ahwitz** [RILMMusicLit/rilm.info-ft#12]

**Comment by northgardner** [comment]
Done.

**Comment by ahwitz** [comment]
is this pushed live?

**Comment by northgardner** [comment]
yes.

**Comment by ahwitz** [comment]
does not look like it - http://mgg-dev.rilm.org/mgg/article?id=mgg08906&format=xml has both the "Moses Mendelssohn" variations visible

**Comment by northgardner** [comment]
https://github.com/RILMMusicLit/rilm.info-ft/blob/master/tei_mgg.css#L476
https://github.com/RILMMusicLit/rilm.info-ft/blob/master/tei_mgg.css#L538

They're there (one of these isn't right though. Let me know which.

**Comment by ahwitz** [comment]
ah, we'd agreed on a slightly different rule - it's rilmPerson > persName[type = 'inverted'/full

**Comment by northgardner** [comment]
OK. Updated and pushed in CSS.

**Comment by ahwitz** [comment]
you deleted that rule for rilmPerson

**Comment by ahwitz** [comment]
you added that rule for docAuthor, removed the docAuthor rule, and didn't add a rilmPerson rule

**Comment by northgardner** [comment]
Now it's pushed.
