### ISSUE TITLE
Consolidate CSS files in root directory of repo

### ISSUE THREAD

**Issue by ahwitz** [RILMMusicLit/rilm.info-ft#17]
@kyarmey - any idea what all of them are and what they're used for? Also want to try to get rid of the `mgg` in the titles there and switch to the `collections` one if possible.

**Comment by kyarmey** [comment]
I don't know if "locations.css" is referenced anywhere. The remainder are Jonathan's demos that are no longer in use.

**Comment by ahwitz** [comment]
`tei_mgg.css` is definitely still in use and referenced by a lot of the MGG docs in MarkLogic right now. do you create the RME ones with references to _collections_ or without references?

**Comment by kyarmey** [comment]
Sorry for the late reply. New RME documents refer only to the .xsd, not to any .css (at least until they're imported to ML--after that, I don't know).

**Comment by ahwitz** [comment]
Above commit removes all the (likely) unused CSS, keeps the copy of the base TEI sheet, and renames `tei-mgg` to `tei-rilm`.

Fairly certain your comment applies to everything; we reference the CSS file in the base XML but we don't actually use it ever. Keeping it around for posterity's sake.
