### ISSUE TITLE
Make tei_mgg-html.css match tei_mgg.css (more or less)

### ISSUE THREAD

**Issue by northgardner** [RILMMusicLit/rilm.info-ft#8]
https://github.com/RILMMusicLit/rilm.info-ft/blob/master/tei_mgg.css
https://github.com/RILMMusicLit/rilm.info-ft/blob/master/tei_mgg-html.css

The second one needs to be made to look like the first one, except for in places where I've put a comment.

**Comment by emoskowitz** [comment]
What are the files that are using these sheets? (So I can test the edits.)

**Comment by ahwitz** [comment]
if Jonathan doesn't get back to you tonight, let me know when you start working next week so I can get you something to test with; there's a few ways to get you this data and I'd rather he pick which to do if he's still here

**Comment by northgardner** [comment]
https://github.com/RILMMusicLit/rilm.info-ft/tree/master/samples
There are two documents there that have both XML and HTML versions.

**Comment by northgardner** [comment]
@emoskowitz: did you get to this at all?

**Comment by northgardner** [comment]
One note here. The bottom section (/_XML only rules_/) needs to be in the HTML css too. (The "XML only" is for the delivery system and this HTML CSS is for the editorial system.)

**Comment by ahwitz** [comment]
(no longer relevant)
