### ISSUE TITLE
Updates for RME title SOL

### ISSUE THREAD

**Issue by kyarmey** [RILMMusicLit/rilm.info-ft#9]
tei_rilm_instructions.html for the /ft folder
opernlexikon.xhtml for the /ft/instructions folder
[tei_rilm_instructions.zip](https://github.com/RILMMusicLit/rilm.info-ft/files/404437/tei_rilm_instructions.zip)

**Comment by northgardner** [comment]
Done. Please confirm that the files are as they should be on the server.

**Comment by kyarmey** [comment]
Perfect. Tnx
